### ISSUE TITLE
Will N2D2 have a Python API in the future?

### ISSUE THREAD

**Issue by cyr6** [CEA-LIST/N2D2#11]
Python is a language that is gaining a lot of interest recently - most of the Neural Networks frameworks (e.g. Caffe and Tensorflow) support Python, which makes it a lot easier to use than C++

Are you planning on adding a Python API for N2D2 in the future?

Thanks for your answer

**Comment by olivierbichler-cea** [comment]
Currently, the primary interfaces for N2D2 are INI configuration files and the native C++ API.
A Python API would certainly be a nice addition but would require quite some work!
Although there is currently no formal dev plan for this, the idea would be to use SWIG for some of the high level N2D2 functions, like the following functions:
```
    Network net;
    std::shared_ptr<DeepNet> deepNet
        = DeepNetGenerator::generate(net, iniConfig);

    deepNet->initialize();
    deepNet->importNetworkFreeParameters("weights_validation");

        deepNet
             ->getStimuliProvider()
                 ->streamStimulus(img, Database::Test);

        deepNet->test(Database::Test);

        std::shared_ptr<TargetScore> targetPicture
            = deepNet->getTarget<TargetScore>();

        const Tensor3d<int> estimatedLabel
            = targetPicture->getEstimatedLabels()[0];
        const Tensor3d<Float_T> estimatedLabelValue
            = targetPicture->getEstimatedLabelsValue()[0];
```
Therefore it would be easy to use N2D2 INI files from Python or others languages, as SWIG supports more than 20 languages!

And of course, it is needless to say we would welcome any contributions on this topic!

**Comment by olivierbichler-cea** [comment]
Hello,
We started integrating a python wrapper to N2D2 with PyBind11 in the latest commit.
Some examples are given in the python folder.
Contributions are still welcome!

**Comment by olivierbichler-cea** [comment]
Closing this issue: a full Python binding + wrapper will be available soon.
