### ISSUE TITLE
Compilation n2d2 : 'runtime_error' is not a member of 'std'

### ISSUE THREAD

**Issue by rattokiller** [CEA-LIST/N2D2#114]
Hi,

I am creating an installation file and a Dockerfile

during my n2d2 install I found myself during 'make' `error: 'runtime_error' is not a member of 'std`

i solved including manually
in Histogram.hpp

in Histogram.hpp :  `#include <stdexcept>`

What system or build version do you use to build n2d2?

Cheers,
Filippo

**Comment by cmoineau** [comment]
Fixed in de1a229ebc51cd1d5ed5e56d844545afe0c7fe7f.
