### ISSUE TITLE
Naming error in the manual and src comments for KITTI dataset (not KITTY) ?

### ISSUE THREAD

**Issue by LucasMahieu** [CEA-LIST/N2D2#13]
HI,
I think there are few mistakes in the manual and in some comments in the code about the name of the KITTI dataset name.

We can find some "KITTY_Road_Database" instead of "KITTI_Road_Database" for example.

Is it an error of naming ? Or is it normal ?

http://www.cvlibs.net/datasets/kitti/eval_road.php

**Comment by olivierbichler-cea** [comment]
Hi,
Thanks for reporting this issue. This was indeed a misspelling!
It is fixed in f4fe14ba52484194c27775457bcf56bebbac1d5c
