### ISSUE TITLE
ActivationFunction for Fully Connected (Fc) layer ?

### ISSUE THREAD

**Issue by LucasMahieu** [CEA-LIST/N2D2#14]
Ji,
It seems that N2D2 treats the option "ActivationFunction" for a layer of type "Fc".
But in the manual, "Fc" layer don't allow the option ActivationFunction.

Is it an oversight into the manual ?

**Comment by olivierbichler-cea** [comment]
Hi,
It was missing in the manual.
This was fixed in 61526d84bbcbb5702921725a4180c8c61bd51519
