### ISSUE TITLE
Blocage lors du lancement de la commande du RUN the learning

### ISSUE THREAD

**Issue by BenDhif** [CEA-LIST/N2D2#18]
Bonjour 
lorsque je lance cette commande 
./n2d2 "mnist24_16c4s2_24c5s2_150_10.ini" -learn 600000 -log 10000
un message d'erreur concernant CUDA s'affiche comme le suivant : 
Option -log: number of steps between logs [10000]
Option -learn: number of backprop learning steps [600000]
Cuda failure: CUDA driver version is insufficient for CUDA runtime version (35) in /home/ahlem/Téléchargements/N2D2-master/include/CudaContext.hpp:34
Error: Cuda failure: CUDA driver version is insufficient for CUDA runtime version (35) in /home/ahlem/Téléchargements/N2D2-master/include/CudaContext.hpp:34

**Comment by olivierbichler-cea** [comment]
Hello,
You probably need to update the NVidia GPU drivers...
This might help: https://stackoverflow.com/questions/41409842/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-vers

**Comment by BenDhif** [comment]
Thank you!

**Comment by olivierbichler-cea** [comment]
The problem appears to be solved, closing the issue.
Please don't hesitate to reopen it if needed!
