### ISSUE TITLE
Erreur "Run the learning"

### ISSUE THREAD

**Issue by BenDhif** [CEA-LIST/N2D2#19]
Bonjour, 
pourriez vous m'aider à résoudre cette erreur du Run the learning

~/Desktop/N2D2-master/bin/exec$ ./n2d2 "mnist24_16c4s2_24c5s2_150_10.ini" -learn 600000 -log 10000Option -log: number of steps between logs [10000]
Option -learn: number of backprop learning steps [600000]
Loading network configuration file mnist24_16c4s2_24c5s2_150_10.ini
Notice: Unused section  in INI file
Time elapsed: 0.000160913 s
Error: Could not open INI file: mnist24_16c4s2_24c5s2_150_10.in

**Comment by olivierbichler-cea** [comment]
Hello,

The first argument of the n2d2 command is the INI file containing the models. Some models are provided in the N2D2/models directory.

You need to provide the correct path to the INI file, or copy the INI file to the n2d2 binary directory.

**Comment by olivierbichler-cea** [comment]
The problem appears to be solved, closing the issue.
Please don't hesitate to reopen it if needed!
