### ISSUE TITLE
Can't download kitti_road dataset

### ISSUE THREAD

**Issue by LucasMahieu** [CEA-LIST/N2D2#21]
When I try to download the KITTI_road dataset with : 
`./tools/install_stimuli_gui.py`
then I have selected KITTI_road dataset 

And I get this error : 

> http://kitti.is.tue.mpg.de/kitti/data_road.zip
> KITTI
> Traceback (most recent call last):
>   File "./tools/install_stimuli_gui.py", line 140, in load_database
>     + urllib.quote(fileName), target, progress)
>   File "/usr/lib64/python2.7/urllib.py", line 94, in urlretrieve
>     return _urlopener.retrieve(url, filename, reporthook, data)
>   File "/usr/lib64/python2.7/urllib.py", line 240, in retrieve
>     fp = self.open(url, data)
>   File "/usr/lib64/python2.7/urllib.py", line 208, in open
>     return getattr(self, name)(url)
>   File "/usr/lib64/python2.7/urllib.py", line 345, in open_http
>     h.endheaders(data)
>   File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
>     self.send(msg)
>   File "/usr/lib64/python2.7/httplib.py", line 826, in send
>     self.connect()
>   File "/usr/lib64/python2.7/httplib.py", line 807, in connect
>     self.timeout, self.source_address)
>   File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
> IOError: [Errno socket error] [Errno -2] Name or service not known

**Comment by olivierbichler-cea** [comment]
Hi,
The download links are no longer valid...
@davidbriand-cea will fix it.

**Comment by davidbriand-cea** [comment]
Hi, thank you for the issue. 
KITTI Road database is now under licensing condition and request an email registration to download it. 
You will have to manually install it from the KITTI website....
To install it you have to follow this link: http://www.cvlibs.net/datasets/kitti/eval_road.php and download the "base kit" of (0.5 GB) (provide the left color images, calibration data and training labels). 
Then extract the downloaded archive at $N2D2_DATA_PATH/KITTI folder.
The next N2D2 commit will provide install informations in the manual.

**Comment by olivierbichler-cea** [comment]
Closing the issue, since it won't be fixed except in the manual.
