### ISSUE TITLE
how to use N2D2 to run on a new AI soc？

### ISSUE THREAD

**Issue by leedykop** [CEA-LIST/N2D2#22]
I have use N2D2 to run on Nvidia Telsa P4 GPU, and I want to run on a new AI soc,in order to compare the performance of them.
How can I use N2D2 to run on a new AI soc,it is also a PCIE card.

**Comment by olivierbichler-cea** [comment]
Hello,
In order to help you, I would need more information about this AI soc. Can you tell us its name?
Or at least its programming model?

**Comment by olivierbichler-cea** [comment]
No more activity, closing the issue.
