### ISSUE TITLE
Error in Build process

### ISSUE THREAD

**Issue by acharyaR** [CEA-LIST/N2D2#23]
During the build process I'm getting the following 

/N2D2-master/src/DeepNet.cpp: In member function ‘void N2D2::DeepNet::cTicks(N2D2::Time_T, N2D2::Time_T, N2D2::Time_T, bool)’:
/home/lonewalker/NN/N2D2-master/src/DeepNet.cpp:2068:13: error: variable ‘itBegin’ set but not used [-Werror=unused-but-set-variable]
             itBegin = mLayers.begin(),
             ^~~~~~~
/home/lonewalker/NN/N2D2-master/src/DeepNet.cpp: In member function ‘void N2D2::DeepNet::initializeCMonitors(unsigned int)’:
/home/lonewalker/NN/N2D2-master/src/DeepNet.cpp:2157:5: error: variable ‘itBegin’ set but not used [-Werror=unused-but-set-variable]
     itBegin = mLayers.begin(),
     ^~~~~~~
cc1plus: all warnings being treated as errors
CMakeFiles/N2D2-OS.dir/build.make:3302: recipe for target 'CMakeFiles/N2D2-OS.dir/src/DeepNet.cpp.o' failed
make[2]: *** [CMakeFiles/N2D2-OS.dir/src/DeepNet.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/N2D2-OS.dir/all' failed
make[1]: *** [CMakeFiles/N2D2-OS.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by olivierbichler-cea** [comment]
Hello,
This will be fixed in the next commit.
You can simply remove the unused variables.
