### ISSUE TITLE
header guard inconsistency

### ISSUE THREAD

**Issue by sfilip** [CEA-LIST/N2D2#28]
Hi,

I believe there is a small problem with a header guard mismatch in include/Generator/LSTMCellGenerator.hpp. Lines 22-23 are:

``
#ifndef N2D2_LSTMCELLGENERATOR_H
``
``
#define N2D2_LSTMVCELLGENERATOR_H
``

The same name should be used on both lines.

**Comment by olivierbichler-cea** [comment]
Fixed, thank you!
