### ISSUE TITLE
Unable to get graphical view (error with gnuplot commands)

### ISSUE THREAD

**Issue by scleyet** [CEA-LIST/N2D2#3]
Running the command: 
`./n2d2.sh "../../../tuto/tutorial.ini" -learn 1 -log 1`

I get lot of errors with gnuplot, here is an example:
```
gnuplot> if (!exists("multiplot")) set term png size 800,600 enhanced large
                                                                      ^
         line 0: unrecognized terminal option
```
Linux distribution: Red Hat Enterprise Linux Server release 6.7 (Santiago)
Gnuplot version: gnuplot 4.6 patchlevel 5

**Comment by olivierbichler-cea** [comment]
Could you send me a full log of the command execution log, including all gnuplot errors?

**Comment by scleyet** [comment]
Find the log here:
[log.txt](https://github.com/CEA-LIST/N2D2/files/1058348/log.txt)

**Comment by olivierbichler-cea** [comment]
It seems that the Gnuplot terminal back-end may not be the right one...
Could you send me the output of this command:
echo 'set terminal' | gnuplot

You may need to install libgd before installing gnuplot:
yum install gd gd-devel

**Comment by olivierbichler-cea** [comment]
Hi, any feedback? Did you manage to solve the issue?

**Comment by scleyet** [comment]
Problem fixed on my side. I used version provided in RedHat distribution instead of other ones installed on my system. 

Thx for support and sorry fro late reply.
