### ISSUE TITLE
How to export to HLS with a board other than KU040/KCU105?

### ISSUE THREAD

**Issue by gabrijob** [CEA-LIST/N2D2#32]
Is there anywhere I can change which board model to export to?

**Comment by davidbriand-cea** [comment]
Hi, the default board is set for a Kintex UltraScale KU040 (on KCU105 evaluation board).
The C_HLS export is provided with a ready to use configuration file "solution.tcl".

This configuration file provides all the directive required for run vivado_hls, the board model can be change at line 13 of this file. You have to replace "xcku060-ffva1156-2-e" by the part name of the board that you want to target.

You can also change design exploration directives that you want provide to vivado_hls. These parameters can be found at the end of the configuration file. The default solution use is "sol_adaptive" which allow a good tradeoff between harware utilization and latency, but other modes can be used between " sol_most_aggressive", "sol_aggressive", "sol_aggressive_constrained", "sol_relaxed", "sol_relaxed_constrained" and "sol_compact". 

The manual will be updated soon for this part.
