### ISSUE TITLE
weights range exceed [-1,1]

### ISSUE THREAD

**Issue by vankhoa21991** [CEA-LIST/N2D2#39]
Hello,
When I train a network with frame_CUDA, and then generate the folder weight_range_normalize for test with spike, sometimes the weight exceed the range [-1,1] and I can not use these weights for spike inference. Do you know about this?
Thanks

**Comment by olivierbichler-cea** [comment]
Hi,
This check is made for behavioral modeling of physical devices. If you don't need that, you can disable the check by adding:
CheckWeightRange=0
at the beginning of your INI file.

**Comment by olivierbichler-cea** [comment]
No further activity, the issue is considered solved. Closing.
