### ISSUE TITLE
Example INI file for CIFAR-10 Dataset

### ISSUE THREAD

**Issue by EdgarLemaire** [CEA-LIST/N2D2#40]
Hello,

I am currently trying to build a network for CIFAR-10 classification. I have tried some different topologies, but I only reach 66,7% on the test dataset (91% on learning) after 48 hours of training. Those topologies were inspired from tensorflow descriptions I could find on the net, but I am quite sure I am missing something as accuracy on test example should be much higher.

Consequently, I was wondering if you had an example INI file for CIFAR-10 (I didn't find any in the models directory) which provides satisfying results.

Thanks in advance,

Regards,

Edgar Lemaire
(PhD student @ Thales Research Technology and LEAT lab, CNRS & Université Cote d'Azur)

**Comment by EdgarLemaire** [comment]
I forgot to mention that I am interested in CNN topologies !

**Comment by olivierbichler-cea** [comment]
Hi,
I just added a simple CIFAR-10 model, which reaches ~85% on test dataset for about 300k parameters. Training time is ~10 min on a Titan X GPU.

**Comment by olivierbichler-cea** [comment]
This issue is considered solved. Please fell free to re-open it if you have further questions.

**Comment by EdgarLemaire** [comment]
Thank you very much Olivier.
