### ISSUE TITLE
Difference between Neuron stats and Synapse stats in stats_spike.log

### ISSUE THREAD

**Issue by vankhoa21991** [CEA-LIST/N2D2#43]
Hello,
I have a question about the difference between the number of output events in the "Neuron stats", and the read events in the "Synapse stats". Could you explain this difference?

Thanks,

**Comment by olivierbichler-cea** [comment]
Hi,
The read events in the "Synapse stats" corresponds to the total number of events received by a synapse, which is shared in a Conv layer. So a synapse can potentially receive input events from any input neuron and is independent of the number of output events in "Neuron stats", which are counted only upon the activation of the neuron, when its membrane potential crosses its threshold.

**Comment by vankhoa21991** [comment]
Thank for your answer.

**Comment by olivierbichler-cea** [comment]
Closing the issue, please feel free to re-open if you have further question on the matter.
