### ISSUE TITLE
C export in integers don't work

### ISSUE THREAD

**Issue by Etienne-DUPUIS** [CEA-LIST/N2D2#44]
C export in integers has stopped working (tested with ` `, `-nbbits 8`, `-nbbits 16` and `-nbbits 32`)

```
$ n2d2 $N2D2_ROOT/models/LeNet.ini -export C
[...]
Exporting Test dataset to "export_C_int8/stimuli"....................
Generating C export to "export_C_int8":
-> Generating cell conv1
Time elapsed: 1.79093 s
Error: Can't export a non-integral double as integral parameter.
```

Step to reproduce:
```
n2d2 N2D2/models/LeNet.ini -learn 6000 -log 3000
n2d2 N2D2/models/LeNet.ini -export C
```

**Comment by olivierbichler-cea** [comment]
@thibaut-cea could you check this issue? It seems related to the latest changes

**Comment by thibaut-cea** [comment]
Thank you for the report. I fixed the error message as it wasn't really clear.

To export a network in integers, the `-calib -1` option is necessary to quantize the network. A value other than -1 and > 0 can be used if you only want to use a part of the test dataset for the calibration.

Could you retry with the command:
`n2d2 $N2D2_ROOT/models/LeNet.ini -export C -nbbits 8 -calib -1`

**Comment by Etienne-DUPUIS** [comment]
Ok with the `-calib -1` it worked, sorry I didn't knew that the calib argument is mandatory
