### ISSUE TITLE
C_HLS export issue

### ISSUE THREAD

**Issue by prachikashikar** [CEA-LIST/N2D2#46]
when I run 'make ./bin/n2d2_test' , I get this displayed,
'cc' is not recognized as an internal or external command,
operable program or batch file.
make: `bin/n2d2_test' is up to date.

How can I fix this?

**Comment by prachikashikar** [comment]
If a try to set CC= gcc in Makefile then the issue is 
E:\set_ups\N2D2\export_C_HLS_int8>make ./bin/n2d2_test
The filename, directory name, or volume label syntax is incorrect.
make: `bin/n2d2_test' is up to date.

Can someone please help me to resolve this?

**Comment by davidbriand-cea** [comment]
Hi, Microsoft Windows operating system is not compatible with the C_HLS export module. You have to use it with a Linux operating system.

**Comment by prachikashikar** [comment]
Oh... Thank you for replying. :)
