### ISSUE TITLE
Missing Modules for C_HLS Export

### ISSUE THREAD

**Issue by weierwan** [CEA-LIST/N2D2#5]
Hi. I'm trying to use the tool to export the trained model into C_HLS codes as shown in the manual. However the tool prompts me that additional modules are needed for the export. I wonder if the module for C_HLS export is missing? It seems the only available export right now is CPP_cuDNN. Thanks.

**Comment by olivierbichler-cea** [comment]
Hello,

While N2D2 is our deep learning open-source core framework, some modules referred as "N2D2-IP" in the manual, are only available through custom license agreement with CEA LIST.

If you are interested in obtaining some of these modules, please contact our business developer for more information on available licensing options:

Sandrine VARENNE (Sandrine.VARENNE@cea.fr)

In addition to N2D2-IP modules, we can also provide our expertise to design specific solutions for integrating DNN in embedded hardware systems, where power, latency, form factor and/or cost are constrained. We can target CPU/DSP/GPU CoTS hardware as well as our own PNeuro (programmable) and DNeuro (dataflow) dedicated hardware accelerator IPs for DNN on FPGA or ASIC.

This is now clarified in the new "About N2D2-IP" section in the manual (rev 8a294d7bef77f9cfbb064df8067c36dca7cc110d).
