### ISSUE TITLE
Downloading MNIST dataset

### ISSUE THREAD

**Issue by prachikashikar** [CEA-LIST/N2D2#52]
Hello, 
Can someone please help me i solving following issue?

prachi@prachi-V530-15ICB:~/N2D2/tools$ python install_stimuli_gui.py
Installation path of the stimuli [default is /local/prachi/n2d2_data]: 
http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
mnist
Traceback (most recent call last):
  File "install_stimuli_gui.py", line 127, in load_database
    os.makedirs(target)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/local'

**Comment by davidbriand-cea** [comment]
Hello,
By default the datasets are downloaded in the path specified in the N2D2_DATA environment variable. If you don't have set this environment variable in your bash, the default value used is "/local/$USER/n2d2_data/.
Here its look like you don't have write access to this path. 

Then you can give you write access to this folder (if you have a root access) or you can set your N2D2_DATA environment variable in your bash to set the path to a folder where you have write access.

**Comment by prachikashikar** [comment]
Thank you.
