### ISSUE TITLE
Downloading MNIST dataset

### ISSUE THREAD

**Issue by prachikashikar** [CEA-LIST/N2D2#54]
Hello I did as you said for #52 . Now when I try to run install_stimuli_gui.py , I get a MNIST file of size of 66 MB , whereas I should get it around 110MB (as per the message on gui). May be this is causing #51 . Can anyone plsease help me on this?

**Comment by Djip007** [comment]
for me 3 weeks ago I get:
```
9912422 23 oct.  00:21  train-images-idx3-ubyte.gz
  28881 23 oct.  00:21  train-labels-idx1-ubyte.gz
```
That need to be unzip 
did you have something else?

**Comment by prachikashikar** [comment]
Hi @Djip007 , thank you for replying. Yes I get these files. I tried this on windows as well but there I was getting proper dataset of images, but on Ubuntu this unzipping is not working. This is what MNIST folder contains after I run install_stimuli_gui.py
![Screenshot from 2019-11-13 10-37-45](https://user-images.githubusercontent.com/55191185/68734814-b8009000-0601-11ea-8081-45b4f703e65f.png)

**Comment by Djip007** [comment]
look good for me... I have that
```
-rw-rw-r--. 1 xxx xxx  7840016 23 oct.  00:16 t10k-images-idx3-ubyte
-rw-rw-r--. 1 xxx xxx  1648877 23 oct.  00:16 t10k-images-idx3-ubyte.gz
-rw-rw-r--. 1 xxx xxx    10008 23 oct.  00:21 t10k-labels-idx1-ubyte
-rw-rw-r--. 1 xxx xxx     4542 23 oct.  00:21 t10k-labels-idx1-ubyte.gz
-rw-rw-r--. 1 xxx xxx 47040016 23 oct.  00:21 train-images-idx3-ubyte
-rw-rw-r--. 1 xxx xxx  9912422 23 oct.  00:21 train-images-idx3-ubyte.gz
-rw-rw-r--. 1 xxx xxx    60008 23 oct.  00:21 train-labels-idx1-ubyte
-rw-rw-r--. 1 xxx xxx    28881 23 oct.  00:21 train-labels-idx1-ubyte.gz
```
look same... 
(and can make training with it...)

**Comment by prachikashikar** [comment]
hey @Djip007 , thanx for your help on all my queries. This issue is solved . Now please help me for this as well, #53 
prachi@prachi-V530-15ICB:~/N2D2/build/bin$ ./n2d2 "mnist24_16c4s2_24c5s2_150_10.ini" -learn 600000 -log 10000
Option -log: number of steps between logs [10000]
Option -learn: number of backprop learning steps [600000]
Loading network configuration file mnist24_16c4s2_24c5s2_150_10.ini
Notice: Unused section  in INI file
Time elapsed: 0.000309111 s
Error: Could not open INI file: mnist24_16c4s2_24c5s2_150_10.ini

**Comment by minhanh2303** [comment]
I have the same error "Error: Could not open INI file: mnist24_16c4s2_24c5s2_150_10.ini". How did you solve this?
