### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by prachikashikar** [CEA-LIST/N2D2#66]
I want to perform some optimization on the learned weights (which are stored as network free parameters in weights_validation directory ). I am creating a new directory (say weights_compressed) after compressing these weights. In this directory, I am generating two text files, for every .syntxt file in weights_validation. How can I use weights from this new directory (weights_compression) to -test a model? Where shall I change the code? Do reply.

**Comment by davidbriand-cea** [comment]
Hi,
You have to use "-w" option as follow : 
./n2d2 -test -w path/to/folder/weights_compression

-w option allow to import weights from a specified location. 
It is also use to perform transfer learning.

**Comment by prachikashikar** [comment]
Thank you @davidbriand-cea  for replying.

Now I want to export the model with these compressed weights. Theoretically, I expect some reduction in model size. With N2D2 how can I check that?
