### ISSUE TITLE
Combinations of model and dataset

### ISSUE THREAD

**Issue by prachikashikar** [CEA-LIST/N2D2#69]
Hi, 

I want to train existing standard models in N2D2 such as squeezNet, ResNet on the datasets other than Imagenet. The datasets should be CIFAR, MNIST, Caltech or any other small dataset in available in N2D2. How should I do that? 

I tried making changes in the INI files of these standard model, to fetch other datasets. But I think it is not that straightforward.

**Comment by EdgarLemaire** [comment]
Hello Prachikashikar,

To use different datasets, you have to set the "database" section of the ini file correctly.
For a built-in dataset :
-first download the dataset using "install_stimuli_gui.py" or "install_stimuli.py" in $N2D2_ROOT/tools
-then change the database section of your inifile accordingly, for example with MNIST :

> [database]
> Type=MNIST_IDX_Database
> Validation=0.2

Warning : for this to work, you have to set the $N2D2_DATA environment variable, and you must download the data in $N2D2_DATA


For a custom dataset :
There is a bit more work. You have to download the dataset by yourself, and organize it with one subfolder per class. The subfolder name will be the class name, and all the data inside this subfolder will be of that class.
Then, configure your database section as follows :

> [database]
> Type=DIR_Database
> DataPath=<path_to_your_dataset_root_folder>
> Learn=0.9
> Validation=0.05 


Keep in mind that you can change the values of Learn and Validation as you wish.

Best regards,


Edgar

**Comment by prachikashikar** [comment]
Thank you @EdgarLemaire  for guiding me on this in such a beautiful way.

**Comment by olivierbichler-cea** [comment]
Considering this issue closed. Please feel free to reopen it if needed.
