### ISSUE TITLE
Weights discretisation not implemented for Frame model

### ISSUE THREAD

**Issue by CapucinedeBoissac** [CEA-LIST/N2D2#8]
Hi,

The weights value discretisation functionality is only applicable with Frame_CUDA model, and not Frame.
Are you planning to add this feature on Frame model?

Thanks in advance,
Capucine

**Comment by olivierbichler-cea** [comment]
Hi, this is now fixed in f0269e9f7fb1fb4494250ae4de8ee97c00d7c5ac.
