### ISSUE TITLE
Unable to CPP Export LeNet

### ISSUE THREAD

**Issue by stephaneburel-cea** [CEA-LIST/N2D2#82]
Hello.
I come to report a bug for CPP export.
When exporting the simple Lenet network :
.n2d2.sh ../../models/LeNet.ini -export CPP -calib -1 -seed 1
The export fails.
The log is :
[error.txt](https://github.com/CEA-LIST/N2D2/files/5694910/error.txt)

Best Regards,
Stéphane Burel

**Comment by olivierbichler-cea** [comment]
Hi,
The export fail because the CPP export currently doesn't support the softmax layer. Indeed, the softmax is hard to quantize and is not useful for inference. The solution is to remove this layer before export.
Olivier

**Comment by olivierbichler-cea** [comment]
Closing the issue as the tool already generate a proper error message.
