### ISSUE TITLE
Problem with SqueezeNet-ONNX CPP Export

### ISSUE THREAD

**Issue by stephaneburel-cea** [CEA-LIST/N2D2#89]
Hello.

I've met a problem with the export of SqueezeNet-ONNX to CPP Export.

Ini File used : models/ONNX/squeezenet-onnx.ini

Command line : ../build/bin/n2d2 squeezenet-onnx.ini -export CPP -dev 6 -calib -1 -act-rescaling-mode Floating-point -no-unsigned -nbbits 8 -w /dev/null -seed 1

Error output : Error: Cell_Frame_CUDA::replaceInput(): can't replace input, the input has not been found.

I have tried this with two onnx model : 
https://github.com/onnx/models/raw/master/vision/classification/squeezenet/model/squeezenet1.0-7.onnx
https://github.com/onnx/models/raw/master/vision/classification/squeezenet/model/squeezenet1.1-7.onnx

The -test command works perfectly fine.

I've not met such problems with others DNNs.

Tried with the latest commit :
4c62e3ac1ad12bb2c4fa4780c6610f20ed583db4
Removed CHECK_CUDA_STATUS to allow CPU execution when CUDA is enabled without CUDA-capable device

Happy Easter !
Stéphane Burel

**Comment by olivierbichler-cea** [comment]
Hi Stéphane,

This issue has been fixed in the latest commit.
Thanks for reporting!

Cheers,
Olivier
