### ISSUE TITLE
Is OpenCV **2.0.0** really required?

### ISSUE THREAD

**Issue by afvincent** [CEA-LIST/N2D2#9]
I just cloned the master branch and tried to install N2D2 following the manual. My first try failed due to (I think) [this line](https://github.com/CEA-LIST/N2D2/blob/master/N2D2.cmake#L56):
```cmake
FIND_PACKAGE(OpenCV 2.0.0 REQUIRED)
```
Indeed I am using Fedora 26, that ships OpenCV 3.2.0. I change the aforementioned line for:
```cmake
FIND_PACKAGE(OpenCV)  # NB: commenting the whole line was not working (CMake newbie...).
```
and the install process went fine. The integrated tests did not fail, and I was able to test the learning on MNIST as described in the manual.

*So if there was no peculiar reason to pin the version of OpenCV to 2.0.0, you might want to get rid of this pinning.*

**Comment by olivierbichler-cea** [comment]
In fact, 2.0.0 is the **minimum** required OpenCV version.
For some reason, CMake is not detecting correctly the version on some systems...

Since OpenCV 2.0.0 is already very old, we dropped the version requirement, as it causes useless issues.
Fixed in 1b54d0ce77af2252f2e10f50f13ce9b7fc459f70.
