### ISSUE TITLE
FORCE N2D2 TO NOT USE CUDA

### ISSUE THREAD

**Issue by DavidBoccara** [CEA-LIST/N2D2#90]
Hello CEA, Is it possible to force N2D2 to use cpu rather than  CUDA ?  My graphics card is too old to operate CUDA 
Thanks for your help

**Comment by olivierbichler-cea** [comment]
Hello,
Yes you can compile N2D2 without CUDA. If you don't have CUDA installed, you can use the CMake directly. If CUDA is installed, there is no flag to disable CUDA with CMake right now, but you can use the Makefile, with the make command and it will compile without CUDA by default (make CUDA=1 to compile with CUDA with the Makefile).
