### ISSUE TITLE
Question about the weights organization

### ISSUE THREAD

**Issue by nassim-abderrahmane** [CEA-LIST/N2D2#93]
Hello,

How the weights are organized in the convolution and fully-connected files (in the files : conv_weights.syntx and fc_weights.syntx)?

Do you confirm that the final weights after learning are stored in 'weights_validation/' folder?

Thank you in advance,
Nassim

**Comment by olivierbichler-cea** [comment]
Hi,
The weights in the 'weights_validation/' folder are saved after the best validation score during the learning (not necessary the last one).
The default organization of the weights is OCHW (output channels, input channels, kernel height, kernel width), but you can change it with the `WeightsExportFormat` INI parameter (see https://cea-list.github.io/N2D2-docs/ini_layers.html#conv). For the fully-connected layer, it is therefore just OC.
Cheers,
Olivier
