### ISSUE TITLE
build error with makefile

### ISSUE THREAD

**Issue by SerenaC94** [CEA-LIST/N2D2#94]
Hi,

I was trying to build N2D2 with the Makefile to avoid issues with CUDA (which I don't need), but there is a recurring error. I removed -Werror to get to the end of the compilation, but I wanted to signal the issue.

```
src/containers/Tensor.cpp:659:16: warning: implicitly-declared ‘N2D2::Tensor<std::shared_ptr<N2D2::CNNIP::Instance> >::Tensor(const N2D2::Tensor<std::shared_ptr<N2D2::CNNIP::Instance> >&)’ is deprecated [-Wdeprecated-copy]
  659 |         return subTensor;
      |                ^~~~~~~~~
src/containers/Tensor.cpp:738:18: note: because ‘N2D2::Tensor<std::shared_ptr<N2D2::CNNIP::Instance> >’ has user-provided ‘N2D2::Tensor<U>& N2D2::Tensor<T>::operator=(const N2D2::Tensor<T>&) [with T = std::shared_ptr<N2D2::CNNIP::Instance>]’
  738 | N2D2::Tensor<T>& N2D2::Tensor<T>::operator=(const Tensor<T>& tensor)
      |                  ^~~~
src/containers/Tensor.cpp: In instantiation of ‘const N2D2::Tensor<U> N2D2::Tensor<T>::rows(size_t, size_t, int) const [with T = std::shared_ptr<N2D2::CNNIP::Instance>; size_t = long unsigned int]’:
src/containers/Tensor.cpp:1007:22:   required from here
```

This is just one instance, but it comes up several times as a warning, and with the Makefile as it is they would all be errors.

**Comment by cmoineau** [comment]
Hi,
We have not been able to observe this behavior, but thank you for notifying us.
If you still observe this error with the most recent version of N2D2, feel free to reopen this issue and give us more details such as the version of GCC you use or some logs. 
Regards,
Cyril
