### ISSUE TITLE
N2D2 is freezing with ResNet101 ONNX Model

### ISSUE THREAD

**Issue by stephaneburel-cea** [CEA-LIST/N2D2#95]
Hello !

The problem occurred with the latest version of N2D2.

When executing N2D2 with ResNet101, with the model downloaded from https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet101-v2-7.onnx

Ini taken from N2D2/models/ONNX/resnet-101-v2-onnx.ini

Used Command : 
n2n2 resnet-101-v2-onnx.ini -test -seed 1

After loading the model, the program freeze after print of [LOG] Layer's receptive fields (receptive_fields.log).

One thread use 100 % from CPU and the program never get out this state.

Tested with resnet101-v2-7.onnx and resnet101-v1-7.onnx.

I did not met such problems with ResNet50-ONNX.

Best Regards,
Stéphane Burel

**Comment by olivierbichler-cea** [comment]
Hello,
Solved in the latest commit.
Thanks.
